# Generated by Django 2.1.5 on 2019-02-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exp', models.IntegerField(default=0)),
                ('domain', models.CharField(max_length=1000)),
                ('designation', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('biodata', models.FileField(upload_to='')),
                ('file_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TempProfileAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exp', models.IntegerField(default=0)),
                ('domain', models.CharField(max_length=1000)),
                ('designation', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('biodata', models.FileField(upload_to='')),
                ('file_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TempProfileDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cil.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='TempProfileEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exp', models.IntegerField(default=0)),
                ('domain', models.CharField(max_length=1000)),
                ('designation', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('biodata', models.FileField(upload_to='')),
                ('file_url', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cil.Profile')),
            ],
        ),
    ]
