# Generated by Django 2.1.5 on 2019-02-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='tempprofileadd',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='tempprofileedit',
            name='file_url',
        ),
    ]
