# Generated by Django 2.1.5 on 2019-02-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cil', '0002_auto_20190210_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biodata',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tempprofileadd',
            name='biodata',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tempprofileedit',
            name='biodata',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
