# Generated by Django 2.1.5 on 2019-02-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cil', '0003_auto_20190213_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biodata',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tempprofileadd',
            name='biodata',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tempprofileedit',
            name='biodata',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
