# Generated by Django 2.1.7 on 2019-02-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cil', '0004_auto_20190216_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='exp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tempprofileadd',
            name='exp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tempprofileedit',
            name='exp',
            field=models.CharField(max_length=20),
        ),
    ]
