# Generated by Django 2.1.7 on 2019-06-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cil', '0009_log_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastSeminars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('conducted_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeminarRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingSeminars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('conducted_by', models.CharField(max_length=100)),
            ],
        ),
    ]
