# Generated by Django 2.1.7 on 2019-06-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cil', '0010_pastseminars_seminarrequest_upcomingseminars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastSeminars',
            new_name='PastSeminar',
        ),
        migrations.RenameModel(
            old_name='UpcomingSeminars',
            new_name='UpcomingSeminar',
        ),
    ]
